### ISSUE TITLE
[FPubD] Error downloading Issuu documents

### ISSUE THREAD

**Issue by sirtenn** [robsonsmartins/php-projects#37]
Hi, Always got the following message:

Error: Error getting publication info. (Code: 0x3). Status: 0 (Not Found). Publication URL:

No matter what kind of browser.

**Comment by robsonsmartins** [comment]
Fixed the problem with Issuu. Also optimized memory usage by compressing images to JPEG before PDF generation.

**Comment by sirtenn** [comment]
Seems it isn't fixed completely, cannot download anything since opening this thread. Same error, same message:
Error: Error getting publication info. (Code: 0x3). Status: 404 (Not Found). Publication URL: <Γ>.
